repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-added-large-files
        - id: detect-private-key
        - id: check-yaml
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
    -   id: black-jupyter
-   repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.10.0
    hooks:
    -   id: markdownlint-cli2-fix
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black"] # to be compliant with black
-   repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
    -   id: docformatter
        exclude: "test_.*"
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args:
          - --max-line-length=89  # to be compliant with black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.960"
    hooks:
    -   id: mypy
        exclude: "(test.*)"
